# 🎀 Rootless, daemonless containers with modern networking.
[containers]
netns = "private"

[engine]
compose_providers = ["podman-compose"]
compose_warning_logs = false
events_logger = "journald"
helper_binaries_dir = ["/usr/lib/podman", "/usr/local/libexec/podman", "/usr/local/lib/podman", "/usr/libexec/podman", "/usr/lib/podman"]

[network]
default_rootless_network_cmd = "pasta"
